### ISSUE TITLE
I can't run the script 

### ISSUE THREAD

**Issue by leofranjav** [Nafidinara/bot-pancakeswap#10]
hello a great greeting, I have been communicating with you in email and following your advice I am here for you to help me solve these problems that you are throwing at me at the time of execution. 

PS C:\bot-pancakeswap-master> npm run snipe

> trading-bot@1.0.0 snipe
> node bot.js

C:\bot-pancakeswap-master\node_modules\@ethersproject\bytes\lib\index.js:9
    return !!(value.toHexString);
                    ^

TypeError: Cannot read property 'toHexString' of undefined
    at isHexable (C:\bot-pancakeswap-master\node_modules\@ethersproject\bytes\lib\index.js:9:21)
    at Object.hexlify (C:\bot-pancakeswap-master\node_modules\@ethersproject\bytes\lib\index.js:165:9)
    at new SigningKey (C:\bot-pancakeswap-master\node_modules\@ethersproject\signing-key\lib\index.js:20:65)
    at new Wallet (C:\bot-pancakeswap-master\node_modules\@ethersproject\wallet\lib\index.js:123:36)
    at file:///C:/bot-pancakeswap-master/bot.js:39:16
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
PS C:\bot-pancakeswap-master>

**Comment by amieycamo** [comment]
Any idea how to solve this error ?

**Comment by amieycamo** [comment]
I came across the same error

**Comment by leofranjav** [comment]
Still trying to solve it, hopefully @Nafidinara tells us about this error.

**Comment by amieycamo** [comment]
we dont need a node inorder to make this work

**Comment by Nafidinara** [comment]
are you have been setup your .env?

**Comment by leofranjav** [comment]
> are you have been setup your .env?

I had badly configured the .env, thank you very much I was able to make it work. I hope soon to be able to gather to access your private repository a big greeting.

**Comment by amieycamo** [comment]
yes I had setup my env .. should i approve my wbnb to busd too as per the front page ?

**Comment by amieycamo** [comment]
and this canbe used only for sniping or can be used for front run too ?

**Comment by amieycamo** [comment]
> are you have been setup your .env?

this means just inputing the informations ryt?

**Comment by amieycamo** [comment]
![image](https://user-images.githubusercontent.com/85048134/120275838-f4b6d980-c2c2-11eb-83e5-a5ff82c844e8.png)


How did u solve this ??
