### ISSUE TITLE
Hi I got a Error  transaction failed: Fail with error 'PancakeRouter: INVALID_PATH'

### ISSUE THREAD

**Issue by ken12332** [Nafidinara/bot-pancakeswap#105]
here is my tran info:  https://www.bscscan.com/tx/0x07f8aeed248f3997bf4b791772134cd02281cb4add9adcaf55e155f2ba60afa2

can you help me?

**Comment by ken12332** [comment]
my env:  BNB_CONTRACT=0x55d398326f99059ff775485246999027b3197955
i use usdt to buy,help my pls!

**Comment by Nafidinara** [comment]
you can't use like that, you can't change BNB address into USDT
