### ISSUE TITLE
How do I do that?  Transfer tokens automatically

### ISSUE THREAD

**Issue by sds3777** [Nafidinara/bot-pancakeswap#114]
My wallet is hacked, all tokens that appear in it the hacker transferred to him manually. I would like to know if there is some way that all the tokens that fall into my wallet would automatically be transferred to my new wallet. I have a friend who was hacked and it seems that his wallet has a bot, if it drops 0.00001 it is automatically sent to another wallet. How do you do this?

**Comment by Nafidinara** [comment]
Please dont make a fud, all source is opened and you can read the code there. there is no something suspicious
