### ISSUE TITLE
 Please help : i am getting this below error and don know where to provide sniping token address and how much to be bought...

### ISSUE THREAD

**Issue by amieycamo** [Nafidinara/bot-pancakeswap#13]
WBNB_CONTRACT=0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
~ WBNB contract for buy the token

FACTORY=0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
~ Pancake Factory contract to get function of buy

ROUTER=0x10ED43C718714eb63d5aA57B78B54704E256024E
~ Pancake Factory contract to process function of buy

YOUR_ADDRESS=
~ Your BSC (BEP20) address from trustwallet or another wallet.

SLIPPAGE=1
~ Customize your slippage here, cannot decimal. (eg : 1, 5, 10). if you buy early token recommended 30+ Slippage

GWEI=5
~ Customize your GWEI (gas fee) here, cannot decimal. (eg : 5, 10, 25). if you buy early token recommended 15+ GWEI

GAS_LIMIT=345684
~ Minimul limit is 210000, more much more better.

MIN_LIQUIDITY_ADDED=3
~ Set how much minimum liquidity added in pair address that you want to buy. set in BNB. (eg : 2, 4, 7).
  2 mean 2 BNB liquidity added.

YOUR_MNEMONIC=
~ Input your private Key here, that you get from your wallet privacy.

**Comment by amieycamo** [comment]
![image](https://user-images.githubusercontent.com/85048134/120275582-9c7fd780-c2c2-11eb-85f6-94d75504f7e6.png)


ALso please i am getting this error

**Comment by Nafidinara** [comment]
you can put it on `to_PURCHASE: 'token you want to snipe'` and how many you will bought on `AMOUNT_OF_WBNB : 'amount you want to buy in WBNB'`

**Comment by amieycamo** [comment]
i don see that option anywhere .. and also i cant rectify this problem shown in the above picture. will be grateful if u can help

**Comment by Nafidinara** [comment]
please find in bot.js
