### ISSUE TITLE
TRANJACTION FAILD

### ISSUE THREAD

**Issue by Anderson-free** [Nafidinara/bot-pancakeswap#14]
There is some issue with the buy function
![image](https://user-images.githubusercontent.com/82789840/120431256-3921a280-c3b3-11eb-9a3f-4bc8db442917.png)
Can you tell me why this issue happen?

**Comment by Nafidinara** [comment]
there are some reason if your tx failed :
you haven't approve your WBNB
your gas price are to small
your GWEI are to small (use 15+ for early token)
your slippage are to small (use 30+ for early token)

**Comment by Anderson-free** [comment]
Can you tell me what do I have to do for your solution?

**Comment by Anderson-free** [comment]
Can you tell me how to approve my bnb?

**Comment by Nafidinara** [comment]
maybe you dont have enough bsc

**Comment by Anderson-free** [comment]
yeah 
So I want you to help me to solve this problem

**Comment by Nafidinara** [comment]
buy bsc for gas fee

**Comment by Anderson-free** [comment]
Do you have any livechat (skype)?
this is my skype address
live:.cid.e349ab3d4be911c9
I want us to discuss more carefully via live chat

**Comment by Anderson-free** [comment]
![image](https://user-images.githubusercontent.com/82789840/120438159-fa441a80-c3bb-11eb-8ff3-c0c603d3cc36.png)
And this errror happen continusly

**Comment by Nafidinara** [comment]
change `initialLiquidityDetected` to false

**Comment by Anderson-free** [comment]
of course, I changed it to false but there is so many errors

**Comment by Anderson-free** [comment]
And do you have skype?
If you have it please contact me

**Comment by Nafidinara** [comment]
> of course, I changed it to false but there are so many errors

what's the error?

**Comment by Nafidinara** [comment]
> And do you have skype?
> If you have it please contact me

Im just have discord, please send you discord username

**Comment by Anderson-free** [comment]
[bot.zip](https://github.com/Nafidinara/bot-pancakeswap/files/6584461/bot.zip)
Hello
This is my source code.
As I mentioned before when I'm going to buy the token in liquidity I can't buy because there are some errors.
But I lost so many transaction fees.
of course, I have 1BNB in Binance Smart Chain Network of metamask
I want you to help and fix my errors
Thanks

**Comment by Nafidinara** [comment]
its free bot, maybe so many bugs here. just tell me the error

**Comment by Anderson-free** [comment]
Did you check my bot.js file?
I have to approve my WBNB by code or another?
As you can see in my first transaction result my bug is TRANSACTION FAIL.
I think maybe it's in router.swapExactTokensForTokens() function
Please help me

**Comment by Nafidinara** [comment]
approve from pancakeswap

**Comment by Anderson-free** [comment]
> approve from pancakeswap

Can you explain this?

**Comment by Nafidinara** [comment]
you can search on google or youtube, sorry for that
