### ISSUE TITLE
Please help i am getting this error

### ISSUE THREAD

**Issue by amieycamo** [Nafidinara/bot-pancakeswap#16]
![image](https://user-images.githubusercontent.com/85048134/120526711-8d944480-c3ea-11eb-86f7-041d2fdedbdd.png)

**Comment by amieycamo** [comment]
amieycamo#1896

sir this is my discord. I would be really grateful if you could help me regarding this issue.

**Comment by Nafidinara** [comment]
please provide you private key in mnemonic not seed phrase

**Comment by amieycamo** [comment]
Sir i gave the private keys but still shows the same error when i write 

 npm run snipe

**Comment by amieycamo** [comment]
would be really helpful if you can help

**Comment by Nafidinara** [comment]
can I see your env?

**Comment by amieycamo** [comment]
WBNB_CONTRACT=0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
FACTORY=0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
ROUTER=0x10ED43C718714eb63d5aA57B78B54704E256024E
YOUR_ADDRESS=0x2C9cF7A6a78f7e490oDa54e4df15F3BBDeE5864e
SLIPPAGE=1
GWEI=5
GAS_LIMIT=345684
MIN_LIQUIDITY_ADDED=3
YOUR_MNEMONIC=3f2490d8b148fda50506c172iaee314e806bd41c23063460d6ded40838c691e3

**Comment by amieycamo** [comment]
PLEASE HELP !!

**Comment by Nafidinara** [comment]
hey you should not give me your mnemonic, its private!

**Comment by Nafidinara** [comment]
what token are you buy?

**Comment by Nafidinara** [comment]
I have been check your wallet address, and its invalid https://www.bscscan.com/address/0x2C9cF7A6a78f7e490oDa54e4df15F3BBDeE5864e

**Comment by amieycamo** [comment]
i did some changes on the mnemonic and address for safety but even though I
do it . i get the same error.
