### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: transaction failed

### ISSUE THREAD

**Issue by Borkuz** [Nafidinara/bot-pancakeswap#17]
I keep getting this error. I approved WBNB, i use the settings below and tried multiple tokens. all give the same error.

`SLIPPAGE=10
GWEI=5
GAS_LIMIT=345684
MIN_LIQUIDITY_ADDED=3`

![anydesk00000](https://user-images.githubusercontent.com/49162416/120535748-a3ead200-c3e3-11eb-9b27-9acbcb1b2eaf.png)

**Comment by Nafidinara** [comment]
Can you send me what token are you buy?

Pada tanggal Kam, 3 Jun 2021 01.50, Borkuz ***@***.***>
menulis:

**Comment by cryptsou** [comment]
Hi, i have the same problem with my bot, can you help me ? 
we thinks its slippage, but his set at 40% and 15gwei ..
Same error like Borkuz

**Comment by Nafidinara** [comment]
So many reason your bot are failed, maybe the token you buy are fluctuative
and so many people buy it at the same time

Pada tanggal Kam, 3 Jun 2021 08.30, cryptsou ***@***.***>
menulis:

**Comment by Borkuz** [comment]
I tried multiple tokens and multiple settings. In slippage gas and gwei. And even on windows and apple. Always get the same error

**Comment by Nafidinara** [comment]
> I tried multiple tokens and multiple settings. In slippage gas and gwei. And even on windows and apple. Always get the same error

what token are you buy?

**Comment by Borkuz** [comment]
i try:
0xb27adaffb9fea1801459a1a81b17218288c097cc
0xe9e7cea3dedca5984780bafc599bd69add087d56
0xb3c430a4e9b7b4d28cfe86fa3db43bd9533fad8d

all give the same error: `Fail with error 'TransferHelper: TRANSFER_FROM_FAILED'`

**Comment by Nafidinara** [comment]
0xb27adaffb9fea1801459a1a81b17218288c097cc Im trying to buy this token, and
everything looks fine, with slippage 15, gwei 5, gas limit 210000. this is
my receipt
https://www.bscscan.com/tx/0x4daefbe332ae1fb38aa8c9474723350ab88b22ed699e2e0de8ccf728e238d
b9e


Pada tanggal Kam, 3 Jun 2021 pukul 14.53 Borkuz ***@***.***>
menulis:

**Comment by Borkuz** [comment]
I use exact same settings, still fails


https://bscscan.com/tx/0x6453e0a96caee7c4f1451ac60885fc00bd843b30a160d4a178a5bc9635f9b622

**Comment by Nafidinara** [comment]
maybe there are some problem in your side, you can read here : How to Fix
"TRANSFER_FROM_FAILED" on PancakeSwap - Followchain
<https://www.followchain.org/transfer-from-failed-pancakeswap/>

Pada tanggal Kam, 3 Jun 2021 pukul 15.42 Borkuz ***@***.***>
menulis:

**Comment by Borkuz** [comment]
I finally found out what the probleem was. I need to have WBNB balance... So I swapped BNB to WBNB and then run the script and it works! Maybe put that in the readme!

**Comment by Nafidinara** [comment]
Wow cool, okay thanks, please

Pada tanggal Kam, 3 Jun 2021 pukul 16.13 Borkuz ***@***.***>
menulis:

**Comment by cryptsou** [comment]
> I finally found out what the probleem was. I need to have WBNB balance... So I swapped BNB to WBNB and then run the script and it works! Maybe put that in the readme! Or change the script to wrap BNB and then buy token

How many WBNB have you ? i have both, BNB and WBNB and stil not work .. slippage 49, gwei 20 gaslimit 600 000... 
not work for early token, but work for BUSD... pls help

**Comment by Borkuz** [comment]
> > I finally found out what the probleem was. I need to have WBNB balance... So I swapped BNB to WBNB and then run the script and it works! Maybe put that in the readme! Or change the script to wrap BNB and then buy token
> 
> How many WBNB have you ? i have both, BNB and WBNB and stil not work .. slippage 49, gwei 20 gaslimit 600 000... 
> not work for early token, but work for BUSD... pls help
> 

Have not tried early token yet..
