### ISSUE TITLE
Did you test the code

### ISSUE THREAD

**Issue by merko232** [Nafidinara/bot-pancakeswap#18]
I see a couple of errors people are running into. Just wondering if you tested the code before.

NB: The links to the important notes are broken. Return a 404

**Comment by Nafidinara** [comment]
Yeah, Im still tested till now, so many reason your transaction are failed,
there is impossible if all your transaction can 100% success

Pada tanggal Kam, 3 Jun 2021 08.19, merko232 ***@***.***>
menulis:
