### ISSUE TITLE
Slippage Tolerance

### ISSUE THREAD

**Issue by bronifaast** [Nafidinara/bot-pancakeswap#19]
hello sir, how do I set unlimited slippage as the router can do? when trying snipping I always fail due to his slippage tolerance![Screenshot_2021-06-03-09-44-06-37.jpg](https://user-images.githubusercontent.com/85243186/120573494-4476db80-c450-11eb-8b05-ba7535445dbc.jpg)

**Comment by Nafidinara** [comment]
How much your slippage?

Pada tanggal Kam, 3 Jun 2021 08.44, bronifaast ***@***.***>
menulis:

**Comment by bronifaast** [comment]
while using your bot I set it to 99, in the router I set 'amountOut', which means it gives me unlimited slippage tolerance

**Comment by Nafidinara** [comment]
yeah you can change `const amountOutMin = amounts[1].sub(amounts[1].div(`${data.Slippage}`)); ` to` const amountOutMin = 0`;

**Comment by bronifaast** [comment]
Okay sir, thank you, I'll give it a try when I get back

**Comment by Nafidinara** [comment]
sure

Pada tanggal Kam, 3 Jun 2021 pukul 15.39 bronifaast <
***@***.***> menulis:
