### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by cainiaokun** [Nafidinara/bot-pancakeswap#2]
Fail with error 'TransferHelper: TRANSFER_FROM_FAILED'

https://bscscan.com/tx/0xd61c4745364aeb6ba7aa7597faa8c0e87071cd293c301a6576380175bf562dd3

i'm trying to buy DOGGY, contract 0x74926b3d118a63f6958922d3dc05eb9c6e6e00c6 but it won't work

help me

**Comment by Nafidinara** [comment]
have you been approve your WBNB on pancake?

**Comment by txxiaokang** [comment]
only wbnb,why not bnb?

**Comment by txxiaokang** [comment]
I just tested it, and I found that it did not monitor the liquidity at all, for the tokens to be issued. I was thinking how to make it monitor the liquidity so that I can buy it in the first time.

**Comment by cainiaokun** [comment]
thank you so much, it worked

i always think wbnb and bnb is the same thing

because my balance is bnb not wbnb, i trade bnb for wbnb to solve this,

but how to use bnb to trade on pancakeswap ?

**Comment by Nafidinara** [comment]
Maybe in the next development I will add trade with other token like BNB or BUSD. Thanks!
