### ISSUE TITLE
PairAddress Not Detected

### ISSUE THREAD

**Issue by merko232** [Nafidinara/bot-pancakeswap#21]
Hello, 

How do I get around the message below.

This is the new coin I was testing with to buy: 0xB46C8c205B3548be511C8616d917BD85F716a28c

pairAddress: 0x0000000000000000000000000000000000000000
pairAddress 0x0000000000000000000000000000000000000000 not detected. Auto restart

**Comment by merko232** [comment]
Never mind

**Comment by nosebleed113** [comment]
how it happen ? can u explain, i wanna learn
