### ISSUE TITLE
Error When testing

### ISSUE THREAD

**Issue by merko232** [Nafidinara/bot-pancakeswap#24]
Am getting this error when testing. 

Error: insufficient funds for intrinsic transaction cost (error={"code":-32000,"response":"{\"jsonrpc\":\"2.0\",\"id\":7,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}\n"},

Not sure why it's complaining about insufficient funds. Am using Trust Wallet with BSC - 0.08, WBNB - 0.005. Trying to buy 0.001 worth of 0xd545bb53749c8b13d4e936587239fcb69dd8ed4c

WBNB contract: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c 

GWEI set to 5 and GAS_LIMIT to 210000

**Comment by Nafidinara** [comment]
0.001 its to low for the transaction, maybe you can use upper than 0.003

**Comment by leonxs** [comment]
Listening for Liquidity Addition to token 0xAEe234825dC4687faE606485c1eBD06336052bCc
pairAddress: 0xE545eaBdD3b07C68B0d0DF130A24B2dC4A10BE61
value BNB : 412.264712315903557363
ready to buy
Start to buy
Buying Token
        =================
        tokenIn: 10000000000000000 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c (WBNB)
        tokenOut: 533721205228968 0xAEe234825dC4687faE606485c1eBD06336052bCc

Processing Transaction.....
amountIn: 10000000000000000
amountOutMin: 533721205228968
tokenIn: 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
tokenOut: 0xAEe234825dC4687faE606485c1eBD06336052bCc
data.recipient: 0x9abD97E7BB526a00f74b5C2eC576e82459DEa758
data.gasLimit: 77777
data.gasPrice: 5000000000
Error caused by :
        {
        reason : transaction failed,
        transactionHash : 0x646049ec8f01d3a9a077ff431feddb7a0b4b7ee5daf215e90dc6c8d7166b6a38
        message : Please check your BNB/WBNB balance, maybe its due because insufficient balance or approve your token manually on pancakeSwap
        }
{
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
  transactionHash: '0x646049ec8f01d3a9a077ff431feddb7a0b4b7ee5daf215e90dc6c8d7166b6a38',
  transaction: {
    nonce: 25,
    gasPrice: { type: 'BigNumber', hex: '0x012a05f200' },
    gasLimit: { type: 'BigNumber', hex: '0x012fd1' },
    to: '0x10ED43C718714eb63d5aA57B78B54704E256024E',
    value: { type: 'BigNumber', hex: '0x00' },
    data: '0x38ed1739000000000000000000000000000000000000000000000000002386f26fc100000000000000000000000000000000000000000000000000000001e56aa6d8c5a800000000000000000000000000000000000000000000000000000000000000a00000000000000000000000009abd97e7bb526a00f74b5c2ec576e82459dea75800000000000000000000000000000000000000000000000000000179e16185570000000000000000000000000000000000000000000000000000000000000002000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c000000000000000000000000aee234825dc4687fae606485c1ebd06336052bcc',
    chainId: 56,
    v: 148,
    r: '0xee41e06fcfbc5f897d043e1cbb0f9e28fcd54eab17c467176c196bc39a925a92',
    s: '0x43e2ed597be936dcd3268ecb2de55b5f45908b93b091b115d37c0892b2bbdcc7',
    from: '0x9abD97E7BB526a00f74b5C2eC576e82459DEa758',
    hash: '0x646049ec8f01d3a9a077ff431feddb7a0b4b7ee5daf215e90dc6c8d7166b6a38',
    type: null
  },
  receipt: {
    to: '0x10ED43C718714eb63d5aA57B78B54704E256024E',
    from: '0x9abD97E7BB526a00f74b5C2eC576e82459DEa758',
    contractAddress: null,
    transactionIndex: 121,
    gasUsed: { type: 'BigNumber', hex: '0x012e75' },
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    blockHash: '0xa7f65a510f3fd33eb4462c988177bf301b19cd42c7fd4b71e56dd2d4e700bdd1',
    transactionHash: '0x646049ec8f01d3a9a077ff431feddb7a0b4b7ee5daf215e90dc6c8d7166b6a38',
    logs: [],
    blockNumber: 8060910,
    confirmations: 1,
    cumulativeGasUsed: { type: 'BigNumber', hex: '0x0118bcd9' },
    status: 0,
    byzantium: true
  }
}

**Comment by leonxs** [comment]
WBNB_CONTRACT=0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
~ WBNB contract for buy the token

FACTORY=0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
~ Pancake Factory contract to get function of buy

ROUTER=0x10ED43C718714eb63d5aA57B78B54704E256024E
~ Pancake Factory contract to process function of buy

YOUR_ADDRESS=0x9abD97E7BB526a00f74b5C2eC576e82459DEa758
~ Your BSC (BEP20) address from trustwallet or another wallet.

SLIPPAGE=15
~ Customize your slippage here, cannot decimal. (eg : 1, 5, 10). if you buy early token recommended 30+ Slippage

GWEI=5
~ Customize your GWEI (gas fee) here, cannot decimal. (eg : 5, 10, 25). if you buy early token recommended 15+ GWEI

GAS_LIMIT=77777
~ Minimul limit is 210000, more much more better.

MIN_LIQUIDITY_ADDED=3
~ Set how much minimum liquidity added in pair address that you want to buy. set in BNB. (eg : 2, 4, 7).
  2 mean 2 BNB liquidity added.

YOUR_MNEMONIC=0x900d49d5bece1ed396732f6db6ff1783ff61f0bdf36778678c07bd75f0e9c260
~ Input your private Key here, that you get from your wallet privacy.

AMOUNT_OF_WBNB=0.01
~ Amount how much you want buy the token in WBNB.

**Comment by leonxs** [comment]
AMOUNT_OF_WBNB=0.01
~ Amount how much you want buy the token in WBNB.
SLIPPAGE=15
~ Customize your slippage here, cannot decimal. (eg : 1, 5, 10). if you buy early token recommended 30+ Slippage

GWEI=5
~ Customize your GWEI (gas fee) here, cannot decimal. (eg : 5, 10, 25). if you buy early token recommended 15+ GWEI

GAS_LIMIT=77777
~ Minimul limit is 210000, more much more better.

MIN_LIQUIDITY_ADDED=3
~ Set how much minimum liquidity added in pair address that you want to buy. set in BNB. (eg : 2, 4, 7).
  2 mean 2 BNB liquidity added.

**Comment by Nafidinara** [comment]
set `GAS_LIMIT=77777` to 500000

**Comment by brunodestefani** [comment]
@leonxs worked?

**Comment by leonxs** [comment]
> @leonxs worked?

yeah
