### ISSUE TITLE
Wont buy, after liquidity is added.

### ISSUE THREAD

**Issue by Borkuz** [Nafidinara/bot-pancakeswap#25]
it keeps saying:
`pairAddress: 0xfDD63AFB71138F5fD7cabCdFdf9f4d9FB65D3C11`
`value BNB : 4854.3232`
`run again...`

token adres is: 0xe5D46cC0Fd592804B36F9dc6D2ed7D4D149EBd6F

**Comment by Borkuz** [comment]
i found a solution, make sure you set `MIN_LIQUIDITY_ADDED` with a decimal, like 2.0 of 5.3

**Comment by Nafidinara** [comment]
yeah, you learn again with by yourself, congrats bro!

**Comment by nosebleed113** [comment]
i got a same problems but change to decimal not work on my case
