### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by leonxs** [Nafidinara/bot-pancakeswap#26]
sry im a JS noob . what does "copy your .env.example to .env" mean? Should i creat a new .env?

**Comment by leonxs** [comment]
i got it fixed. thank u!

**Comment by Jreza** [comment]
just delete .example

**Comment by leonxs** [comment]
How can i set it to use BNB to buy new coins?

**Comment by Borkuz** [comment]
You can't, just wrap BNB on pancakeswap

**Comment by leonxs** [comment]
got it , thank u sir.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nafidinara/bot-pancakeswap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nafidinara/bot-pancakeswap] issue (#26)





 
You can't, just wrap BNB on pancakeswap
