### ISSUE TITLE
Problem, can someone help?

### ISSUE THREAD

**Issue by dxspgs** [Nafidinara/bot-pancakeswap#27]
![image](https://user-images.githubusercontent.com/42302687/120934062-7f556980-c705-11eb-843d-a53735966f01.png)

**Comment by Borkuz** [comment]
Did you run npm install? Did you rename .env.example to .env ?

**Comment by dxspgs** [comment]
> Did you run npm install? Did you rename .env.example to end   
![image](https://user-images.githubusercontent.com/42302687/120934210-10c4db80-c706-11eb-8cd8-7aa9da31d524.png)
end.js  ??

**Comment by dxspgs** [comment]
> Did you run npm install? Did you rename .env.example to .env ?

maybe do oy haave discord?

**Comment by Randomized2** [comment]
Hello, did you solve this problem? I have the same exact problem and I would like to know how you did thank you.

**Comment by Nafidinara** [comment]
have you been set your mnemonic?

**Comment by dxspgs** [comment]
> have you been set your mnemonic?

i should use key mnenmonik or mnemonik words?

**Comment by dxspgs** [comment]
> Hello, did you solve this problem? I have the same exact problem and I would like to know how you did thank you.

no

**Comment by Nafidinara** [comment]
> > have you been set your mnemonic?
> 
> i should use key mnenmonic or mnemonic words?

private key

**Comment by dxspgs** [comment]
> > > have you been set your mnemonic?
> > 
> > 
> > i should use key mnenmonic or mnemonic words?
> 
> private key

![image](https://user-images.githubusercontent.com/42302687/121190844-1a6c5180-c874-11eb-92b8-27d638f31150.png)

**Comment by Nafidinara** [comment]
can you paste here the error?

**Comment by dxspgs** [comment]
> can you paste here the error?

maybe i can communicate with you in discord?

**Comment by Nafidinara** [comment]
A algarox#0785

**Comment by dxspgs** [comment]
> A algarox#785

chupakabra#8743  cant find this is my

**Comment by dxspgs** [comment]
> A algarox#785

[2021-06-08T16_08_23_844Z-debug.log](https://github.com/Nafidinara/bot-pancakeswap/files/6618068/2021-06-08T16_08_23_844Z-debug.log)
this is debulog

**Comment by Randomized2** [comment]
Hey, I have the same problem and I think I used mnemonic words, is metamask compatible with the bot or should I use another wallet.

**Comment by Borkuz** [comment]
> Hey, I have the same problem and I think I used mnemonic words, is metamask compatible with the bot or should I use another wallet.

You must use your private key not the mnemonic words this wil not work. in Metamask you go to acount setting -> export private key

**Comment by dxspgs** [comment]
> > Hey, I have the same problem and I think I used mnemonic words, is metamask compatible with the bot or should I use another wallet.
> 
> You must use your private key not the mnemonic words this wil not work. in Metamask you go to acount setting -> export private key

i using private key

**Comment by rekaa0251** [comment]
Your node version is too old, upgrade and you will not get this error.

**Comment by dxspgs** [comment]
> Your node version is too old, upgrade and you will not get this error.
> 
> edit: looks like u also have wrong key

this key worked well with another one bot but not with that,
