### ISSUE TITLE
Error at using npm run sniper

### ISSUE THREAD

**Issue by dethkarpp** [Nafidinara/bot-pancakeswap#29]
I get this errors when I run it. Any idea what I'm doing wrong? 

![image](https://user-images.githubusercontent.com/85545283/121136719-3e10a700-c836-11eb-9ba0-70c40a7f80aa.png)

**Comment by Borkuz** [comment]
Dit you run npm install in the bot folder? Are you using the latest package.json?

**Comment by Godxia** [comment]
I get the same problem

**Comment by Borkuz** [comment]
Did you rename .env.example to .env and edited the file with the correct settings

**Comment by Nafidinara** [comment]
thanks @Borkuz for helping me answer the question
