### ISSUE TITLE
Getting an error when 

### ISSUE THREAD

**Issue by huzansheesh** [Nafidinara/bot-pancakeswap#30]
I keep getting this error when sniping. Any idea why this might be?
I have the following set:
SLIPPAGE=49
GWEI=30
GAS_LIMIT=3456840
![Uploading Screen Shot 2021-06-08 at 4.44.40 AM.png…]()

**Comment by huzansheesh** [comment]
<img width="436" alt="Screen Shot 2021-06-08 at 4 44 40 AM" src="https://user-images.githubusercontent.com/85380924/121154159-b7979d80-c814-11eb-9123-69671f9e0ea4.png">

**Comment by Borkuz** [comment]
Slippage to low

**Comment by huzansheesh** [comment]
Aah ok. Borkuz, do you know how high the slippage can be set?

**Comment by huzansheesh** [comment]
Any idea? From what I checked pancake swap only allows 49%

**Comment by huzansheesh** [comment]
I had a look again, and noticed this has already been solved.
