### ISSUE TITLE
Bot error npm run snipe

### ISSUE THREAD

**Issue by Randomized2** [Nafidinara/bot-pancakeswap#34]
![bot error](https://user-images.githubusercontent.com/85532160/121453159-87a3e380-c955-11eb-8aa2-001e0bae2a77.png)
Hello, sorry to constantly ask questions, but I also encountered a problem that has been constantly posted already. I can't seem to run the snipe bot, I've approved the wbnb, entered a private key, and renamed the env.example. file. Is there any other problems that I might of missed to lead to this problem? Thanks.

**Comment by Nafidinara** [comment]
Can see your folder structure?

Pada tanggal Kam, 10 Jun 2021 09.06, Randomized2 ***@***.***>
menulis:

**Comment by Randomized2** [comment]
Uh should I give you my file? Do you have telegram or discord to talk?

**Comment by Nafidinara** [comment]
Yeah you can touch me via discord ( A algarox#0785 )

Pada tanggal Kam, 10 Jun 2021 12.04, Randomized2 ***@***.***>
menulis:
