### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by marocsvinicious** [Nafidinara/bot-pancakeswap#35]
Hello Alfara Nafi Dinara, 

First of all I would like to thank you for making Bot PancakeSwap available for free. I confess that I had some difficulties with installing helpers such as nodejs, as well as updating it so that it could run with excellence or bot, but I managed and everything worked.

Well, I managed to execute an order very quickly when I ran the bot. However, I suggested some doubts that I inevitably need to resolve with you brilliant creator of the bot.

The questions are:

1) Is there the possibility of placing only the BNB as a bargaining chip and removing the WBNB? Because, with WBNB, manual approval is required and this decreases the bot's agility, as it does not do this automatic approval and without approval the transaction is unsuccessful.

2) I realized that when executing the bot with the buy order, automatically the next phase is to wait for a reasonable price for a profitable sale. Wanted to know how I set the profit percentage or even how do I know what percentage is preset in the bot?

**Comment by Nafidinara** [comment]
Hello, your questions is ready on the advanced bot right now

**Comment by marocsvinicious** [comment]
How can I access the advanced version?

**Comment by brunodestefani** [comment]
@marocsvinicious cuidado man, os contratos do arquivo .env estão cheio de comentários no bscscan que é scam!

**Comment by Nafidinara** [comment]
Hello, I have been reply your message via discord

Pada tanggal Sen, 14 Jun 2021 07.53, brunodestefani <
***@***.***> menulis:
