### ISSUE TITLE
Eror when i running bot.js

### ISSUE THREAD

**Issue by MrHaans** [Nafidinara/bot-pancakeswap#36]
Please explain me to fix this eror, thankyou

![image](https://user-images.githubusercontent.com/55905766/121819404-1c407580-ccb7-11eb-8fa5-3317de93d691.png)

**Comment by Nafidinara** [comment]
setup your env carefully, change .env.example to .env via visual studio code

Pada tanggal Sen, 14 Jun 2021 pukul 02.20 Ahmad Farhan <
***@***.***> menulis:

**Comment by brunodestefani** [comment]
Be careful ! The contracts in the .env have a lot of comments of scamming.

**Comment by Nafidinara** [comment]
You can see the whole of code, so you can check its a scam or not

Pada tanggal Sen, 14 Jun 2021 07.52, brunodestefani <
***@***.***> menulis:

**Comment by bbgunxx** [comment]
.
