### ISSUE TITLE
New feature request: mempool sniping

### ISSUE THREAD

**Issue by Borkuz** [Nafidinara/bot-pancakeswap#38]
Is it possible to get mempool sniping in the future. Since regular liquidity sniping is used alot these days it is getting harder to get successful Snipes. Mempool Snipes work 99% of the time. As seen in this video: https://streamable.com/bsh9hg

Explained here:
https://www.quicknode.com/guides/defi/how-to-access-ethereum-mempool

**Comment by Nafidinara** [comment]
Yeah, we have been do this at advanced bot

**Comment by Borkuz** [comment]
> Yeah, we have been do this at advanced bot

please let me know if it is available in the advanced bot. I'm definitely interested

**Comment by Nafidinara** [comment]
yap. its now available
