### ISSUE TITLE
Is there a reason for the Timeout?

### ISSUE THREAD

**Issue by heycryptobob** [Nafidinara/bot-pancakeswap#41]
Hello - I'm just trying to understand what the reason is behind the Timeout of 3000 ms. Thanks!

https://github.com/Nafidinara/bot-pancakeswap/blob/dfd09332be420c4dec1805d3a21922eb5fb6f8f8/bot.js#L90

**Comment by Nafidinara** [comment]
its just timeout to delay buy action, you can change like what you want
