### ISSUE TITLE
private key?

### ISSUE THREAD

**Issue by emveeq** [Nafidinara/bot-pancakeswap#43]
do we really need to input that?

**Comment by Nafidinara** [comment]
yes you need to input a private key to connect to your wallet. we prefer
you using second wallet with low balance

Pada tanggal Jum, 18 Jun 2021 pukul 21.29 emveeq ***@***.***>
menulis:

**Comment by emveeq** [comment]
oh okay will try this with other wallet i guess. thanks!

**Comment by Nafidinara** [comment]
With my pleasure bro

Pada tanggal Jum, 18 Jun 2021 pukul 21.42 emveeq ***@***.***>
menulis:
