### ISSUE TITLE
It never works the first time

### ISSUE THREAD

**Issue by DJosh7** [Nafidinara/bot-pancakeswap#50]
Hey there, 

I have to launch the bot several times for it to be able to effectively snipe 

Always have a "Call Exception" error on the bot and "INSUFFICIENT_OUTPUT_AMOUNT" on bscscan

Any idea ?

**Comment by Nafidinara** [comment]
how much you have BNB and WBNB?

**Comment by Nafidinara** [comment]
try to buy token manually with WBNB first, then try again
