### ISSUE TITLE
Impossible to add custom node 

### ISSUE THREAD

**Issue by DJosh7** [Nafidinara/bot-pancakeswap#51]
Hey there ! 

Does anybody know exactly how to put our own node on the code ?

I put the "wss" address at the right place but then the bot doesn't work 

<img width="388" alt="Capture d’écran 2021-06-26 à 15 50 06" src="https://user-images.githubusercontent.com/86615128/123661031-7a7f6380-d834-11eb-85f7-75044c8d5756.png">

**Comment by Nafidinara** [comment]
maybe there is some error with your node. you can change in `wss` variable

**Comment by Nafidinara** [comment]
HI, I see many of yours get same problem, check this to solve : https://github.com/Nafidinara/bot-pancakeswap#TROUBLESHOOT
