### ISSUE TITLE
approving issue for snipe new coin 

### ISSUE THREAD

**Issue by 0xE1C9** [Nafidinara/bot-pancakeswap#54]
Hay, I tried to snip coin with no leq, I tried to approve the wbnb in pancake V1 cuz I didn't get it in V2 

is there any suggestion on how to buy a new coin without the approving issue? 

thanks 

 transactionHash: '0xca805febb0e2302e7d9d1a602a1959221c31ddfb8d15364adc4101fe9b679817'

**Comment by Nafidinara** [comment]
we are you using V2, try to buy token manually first with WBNB
