### ISSUE TITLE
Uniswap support

### ISSUE THREAD

**Issue by babaalidev** [Nafidinara/bot-pancakeswap#56]
Hello, 
nice bot. Can i also use it with Uniswap?
How can i do it?

Thank you

**Comment by babaalidev** [comment]
And how about Matic, Quickswap?

**Comment by Nafidinara** [comment]
No, you just only can use for pancakeswap

Pada tanggal Sab, 3 Jul 2021 pukul 19.55 babaalidev <
***@***.***> menulis:

**Comment by babaalidev** [comment]
Why not uniswap? Shouldnt it be able to use uniswap, because i heard pancakeswap cloned uniswap. Just change network?

**Comment by LLemon199** [comment]
Uniswap here: https://github.com/LLemon199/pancake-uniswap-sniping-bot

**Comment by Nafidinara** [comment]
Thanks for the reference

Pada tanggal Sen, 5 Jul 2021 02.05, Lemon ***@***.***>
menulis:
