### ISSUE TITLE
pairAddress 0x0000000000000000000000000000000000000000 not detected. Restart me!

### ISSUE THREAD

**Issue by rakage** [Nafidinara/bot-pancakeswap#6]
Hello, im having this trouble and i have no idea how to fix it. 
http://prntscr.com/136a0og
Can you help me?
Thanks

**Comment by Nafidinara** [comment]
it mean there is no pair for that token, just wait until the dev add pair. try to pull again

**Comment by rakage** [comment]
How do i know if the dev added a pair?

**Comment by Nafidinara** [comment]
just wait until the bot find it, or you can check in : https://bscscan.com/address/0xca143ce32fe78f1f7019d7d551a6402fc5350c73#readContract on getPair function

**Comment by rakage** [comment]
should i restart (close and open again) or just wait for the bot to detect it?

**Comment by Nafidinara** [comment]
no, just wait the bot detect
