### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by borahanarslan** [Nafidinara/bot-pancakeswap#63]
It's not working anymore for the last 2 days. I think some updates are needed. 

We tried it for 14 different tokens in 4 different wallets, it used to work but for the last 2 days it returns the same error for all wallets

My Wallet : https://bscscan.com/address/0x254f8b6Cf356DbaA754a34CFe2fB672F3E08e063
![image](https://user-images.githubusercontent.com/14363652/126308136-6c639fbd-26af-4eb3-bd08-e9be29a05279.png)
![image](https://user-images.githubusercontent.com/14363652/126308532-6ca6ab7d-80ac-4dd6-b0bc-26700c104642.png)

**Comment by borahanarslan** [comment]
![image](https://user-images.githubusercontent.com/14363652/126306695-15d380ee-4618-44c4-8d6e-fd81c806455b.png)

**Comment by Nafidinara** [comment]
Hi, can you send me some example of tx hash
