### ISSUE TITLE
Error : Cannot find module "dotenv/config

### ISSUE THREAD

**Issue by Trinhhoanglong1610** [Nafidinara/bot-pancakeswap#77]
It keep popping this error. Please help. Really apperciate your works here. Thank a lots sir 👍 

![12312412](https://user-images.githubusercontent.com/88970314/129489495-723ebccf-7644-4f53-bf71-e820e512750c.PNG)

**Comment by vanvinh18i2** [comment]
> Bác ơi có bán dùng chung được ko bác

ib tele @chumamimunhanho e share giá rẻ
