### ISSUE TITLE
I CAN NOT MOVE ARROW KEYS, IT ALWAYS SELL 

### ISSUE THREAD

**Issue by huyharris** [Nafidinara/bot-pancakeswap#78]
![image](https://user-images.githubusercontent.com/88964028/129553622-a7d0d7a9-62d2-4fa3-967d-e3085eaab863.png)
Why I can not move arrows key to BUY or anyelse BUTTON, when only I move the mouse to BUY and press ENTER, it just only SELL although I want to press BUY ?

**Comment by Nafidinara** [comment]
please contact me on discord (A algarox#0785)

**Comment by Nafidinara** [comment]
please contact me on discord : A algarox#0785

Pada tanggal Kam, 26 Agu 2021 pukul 22.12 Hoàng Thành <
***@***.***> menulis:
