### ISSUE TITLE
Transfer from failed error

### ISSUE THREAD

**Issue by ikhwanb** [Nafidinara/bot-pancakeswap#9]
Hi. Seeking assistance to solve error:

Fail with error 'TransferHelper: TRANSFER_FROM_FAILED'
as per tx
https://bscscan.com/tx/0x635dbe546d61c23a51c68e9fce019464afb5a73c10aa1aa9b3bbfd1718ecc2cd

btw, love the code super clean. thanks a lot!

**Comment by Nafidinara** [comment]
there are some reason if your tx failed : 
1. you haven't approve your WBNB
2. your gas price are to small
3. your GWEI are to small (use 15+ for early token)
4. your slippage are to small (use 49 for early token)

**Comment by Anderson-free** [comment]
Can you tell me how to approve my WBNB?
And above condition's meaning?

**Comment by Nafidinara** [comment]
> Can you tell me how to approve my WBNB?
> And above condition's meaning?

you can read readme please

**Comment by ikhwanb** [comment]
awesome will try it. thanks a lot
