### ISSUE TITLE
PancakeRouter: INVALID_PATH

### ISSUE THREAD

**Issue by sergeevtoll** [Nafidinara/bot-pancakeswap#96]
i take error "Fail with error 'PancakeRouter: INVALID_PATH'" on BSC. And console "transaction failed". What happen wrong?
transaction: https://bscscan.com/tx/0x47e8f5407f884a4cfdadf75925bb103b0ad1980bb94ba5f27af3ab1ebb621139

**Comment by Nafidinara** [comment]
try to setting env carefully
