### ISSUE TITLE
Mnemonic?

### ISSUE THREAD

**Issue by vmajor** [Nafidinara/bot-pancakeswap#97]
Why are you asking for the mnemonic phrase? The only valid reason for this is wallet recovery, or wallet theft. Thus please comment otherwise this looks like a scam project.

**Comment by DonSYS91** [comment]
@vmajor how should they access your finds? they're not asking for the phrase but for the private key because the bot need to programmatically access your wallet to spend.

**Comment by Nafidinara** [comment]
yes, we dont have access to do that, the bot is 100% yours
